### ISSUE TITLE
other dataset such as celebA will train a result?

### ISSUE THREAD

**Issue by zdx3578** [anibali/infogan#1]
other dataset such as celebA will train a result?

**Comment by anibali** [comment]
You're welcome to give it a try, the only other dataset I have played around with is CIFAR-10. You will need to use your own CelebA data loader in place of `MnistDataset` (https://github.com/anibali/infogan/blob/dbfe8ad5651efef761e7b879d5d956c4d1a7faf7/bin/train_infogan.lua#L68). You also might want to play around with the structure of the salient variables.
