### ISSUE TITLE
the meaning of --gen-inputs (default 74)？

### ISSUE THREAD

**Issue by KangolHsu** [anibali/infogan#3]
Do you mean the number of  z and c  is 74，the first 2 value of the gen-inputs is the salient-vars, am i right?
thank you

**Comment by anibali** [comment]
Almost. You are correct in that it is the number of dimensions required to represent both the noise variables (z) and salient variables (c). However, in the default case at time of writing, 62 dimensions are noise and 12 salient (10 for categorical + 2 for uniform).
